//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Van_Dip
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ID_Yonman { get; set; }
        public int ID_School { get; set; }
        public int ID_Ryk { get; set; }
    
        public virtual Ryk Ryk { get; set; }
        public virtual Schoo Schoo { get; set; }
        public virtual Yonman Yonman { get; set; }
    }
}
