//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Van_Dip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ryk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ryk()
        {
            this.List = new HashSet<List>();
        }
    
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int School { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List> List { get; set; }
        public virtual Schoo Schoo { get; set; }
    }
}
