//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Van_Dip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yonman()
        {
            this.List = new HashSet<List>();
        }
    
        public int ID { get; set; }
        public string Firstna { get; set; }
        public string Firstnam { get; set; }
        public string Firstname { get; set; }
        public string Rodd { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public int School { get; set; }
        public string Phone { get; set; }
        public string Characteristic { get; set; }
    
        public virtual Schoo Schoo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List> List { get; set; }
    }
}
